### ISSUE TITLE
mount and unmount js plugins

### ISSUE THREAD

**Issue by sadeghbarati** [giantcz/gia#2]
hey thanks for Swup it very awesome :heart: 

but this `Gia` is very confusing how can I use Gia for js plugins like `glide.js` or `select2` and another js plugins

and how integrate loadComponents with Swup reinit function `contentReplaced`

**Comment by AugustMiller** [comment]
Hey! Quick answer for your second question: There's an official [Gia plugin for Swup](https://swup.js.org/plugins/gia-plugin) that handles the call to `loadComponents()` automatically. Keep in mind that if you've loaded any components outside your defined `containers`, you'll be responsible for re/initializing them whenever appropriate (usually, this is just once when the page is cold-loaded, but your needs may differ).

Here's a quick example of a config that implements `SwupGiaPlugin`:

```js
import Swup from 'swup';
import SwupGiaPlugin from '@swup/gia-plugin';
import { loadComponents } from 'gia';

import MyComponent from './components/MyComponent';

const components = {
    MyComponent
};

// Start up Swup so future navigations don't destroy the thread:
const swup = new Swup({
    containers: [
        '#my-container'
    ],
    plugins: [
        new SwupGiaPlugin({ components, firstLoad: false })
    ]
});

// Misc. stuff that should happen after every "init" (and after Components have been mounted)
const afterInit = (e) => {
    // Up to you!
};

// Trigger those when Swup issues a `contentReplaced` event:
swup.on('contentReplaced', afterInit);

// First load should initialize components *everywhere*, not just within Swup containers (optional if you instead have `firstLoad: true` set in SwupGiaPlugin options, but not if you need to initialize stuff outside the set Swup `containers`):
loadComponents(components);

// Call our post-init hook once, manually:
afterInit();
```

As for using third-party plugins, it's apt to follow the same pattern as suggested in their documentation. Say you have a `Select` component imported and added to your `components` object, above:

```js
import { Component } from 'gia';

export default class Select extends Component {
    constructor ($el) {
        super($el);

        this.ref = {
            $menu: null
        };
    }

    mount () {
        // Assuming jQuery and Select2 are available globally, and their `script` tags appear earlier in the `<head>` than your custom/app bundle:
        $(this.ref.$menu).select2();
    }
}
```

Your Component will get unmounted, and re-instantiated whenever it appears on the page.

```html
<div g-component="Select">
    <select g-ref="Select:$menu">
        <!-- Your Options -->
    </select>
</div>
```

(Also, worth noting that you could just drop any Select2 initializers in the `afterInit(…)` function in the first code block—it doesn't have to be wrapped in a component!)
