### ISSUE TITLE
use one Gia component for many element

### ISSUE THREAD

**Issue by sadeghbarati** [giantcz/gia#3]
I recently use GIA to creating `modal` for **`3 elements`**

actually, I use `document.querySelectorAll()` for register events like click for each element have `g-components`

but each event runs **`3 time`**

``` html
<button g-component="SampleComponent" data-modal-target=".dialog-1"></button>
<button g-component="SampleComponent" data-modal-target=".dialog-2"></button>
<button g-component="SampleComponent" data-modal-target=".dialog-3"></button>
```

``` javascript

import Component from 'gia/Component';

class SampleComponent extends Component {
    constructor(element, options) {
        super(element);
        this.dialogs = []
        this.options = {
            someOptions: "customValue"
        };
    }
    mount() {
        this.dialogs = document.querySelectorAll('[data-modal-target]');
        this.registerEvents();
    }
    registerEvents() {
        this.dialogs.forEach((items, index) => {
            items.addEventListener('click', this.handleClick.bind(this));
        })
    }
    handleClick() {
        alert('ALERT TRIGGER 3 TIME')
    }
}
export default SampleComponent
```
---
`3` Created instance of component "SampleComponent".

**Comment by sadeghbarati** [comment]
@gmrchk 

If want to GIA works well have to register GIA components with a different name with same code :disappointed:

**Comment by sadeghbarati** [comment]
[Codepen Demo](https://codepen.io/riccardo051/pen/NWKEOYp) **`GIA Component + loadComponents`**

**Comment by gmrchk** [comment]
Your problem is using the `document.querySelectorAll` in the component, you're basically searching for any occurrences in dom and breaking that component logic.

Replace it with `this.element.querySelectorAll` instead.

Or even better, use the [built-in function](https://github.com/giantcz/gia#ref) for getting element reference.

**Comment by sadeghbarati** [comment]
@gmrchk 

the solution above solve my problem but I have `2 questions`
-----
**`questions 1:`**

I using refs `multipleRefs` like [this](https://github.com/giantcz/gia#ref)
I stored the `multipleRefs` in array

and call event forEach element in `multipleRefs` everything is fine 
alerts do not trigger 3 time

but how to getAttribute with $(this) I use jQuery format to understand what I mean


``` html
<div g-component="SampleComponent">
    <h1 g-ref="multipleRefs">asd</h1>
    <h1 g-ref="multipleRefs">asd</h1>
    <h1 g-ref="multipleRefs">asd</h1>
</div>
```

``` javascript 
class SampleComponent extends Component {
    constructor(element, options) {
        super(element);
        this.ref = {
        multipleRefs: [],
      }
    }
    mount() {
      this.ref.multipleRefs.forEach((items, index) => {
            items.addEventListener('click', this.handleClick.bind(this));
       })
    }
    handleClick() {
     **my problem how to use $(this).getAttribute ?**

      const attr = this.getAttribute("any-attr");
      console.log(attr)
  }
}

const component = {
    "SampleComponent": SampleComponent
}

document.addEventListener('DOMContentLoaded', function() {
    loadComponents(component);
})
```

-----
**`questions 2:`**

I'm using the same component on `two-element` `header` & `footer`
and i got error with Triggers

``` html 
<header g-component="SampleComponent">
    <h1 g-ref="multipleRefs">asd</h1>
    <h1 g-ref="multipleRefs">asd</h1>
    <h1 g-ref="multipleRefs">asd</h1>
</header>

<footer g-component="SampleComponent">
    <h1 g-ref="multipleRefs">asd</h1>
    <h1 g-ref="multipleRefs">asd</h1>
    <h1 g-ref="multipleRefs">asd</h1>
</footer>
```
if i want to component works well i have to set g-component on body tag 

``` html 
<body g-component="SampleComponent">
    <header>
        <h1 g-ref="multipleRefs">asd</h1>
        <h1 g-ref="multipleRefs">asd</h1>
        <h1 g-ref="multipleRefs">asd</h1>
    </header>

    <footer>
        <h1 g-ref="multipleRefs">asd</h1>
        <h1 g-ref="multipleRefs">asd</h1>
        <h1 g-ref="multipleRefs">asd</h1>
    </footer>
</body>
```


pls provide more example or advance example for Amateurs like me :(

**Comment by sadeghbarati** [comment]
@gmrchk pls help

Regards :+1:
