### ISSUE TITLE
async and await Question

### ISSUE THREAD

**Issue by sadeghbarati** [giantcz/gia#6]
Hi @gmrchk @AugustMiller

I'm using `webpack` and use `async` require

[like your website](https://plzen.cz.panasonic.com/) async and await `flickity` plugin

only thing I need is what is your webpack or babel `configuration` and how to do it in new babel(7)
or even a simple `webpack starter` with `gia` and simple example of `async await` in it

I got this error 
`this.flickity is not a function`
in both mode of webpack `development` and `production`

``` javascript
key: "require",
  value: (o = regeneratorRuntime.mark((function t() {
    return regeneratorRuntime.wrap((function(t) {
      for (;;)
        switch (t.prev = t.next) {
          case 0:
            return t.next = 2,
              Promise.resolve().then(n.t.bind(null, 24, 7));
          case 2:
            this.flickity = t.sent;
          case 3:
          case "end":
            return t.stop()
        }
    }), t, this)
```

pls help thanks

**Comment by sadeghbarati** [comment]
#1

**Comment by sadeghbarati** [comment]
I still confuse what is default on end 

this.swiper.default


@gmrchk in #1 you said I like have place to importing component dependency 


can you explain pls ?

**Comment by AugustMiller** [comment]
This strikes me as a Webpack or Babel issue, not a Gia issue.

I haven't personally used async require, as the normal `import` directive seems to work just fine—so, I can't be of much help, sorry!

**Comment by gmrchk** [comment]
There is literally a [demo repo](https://github.com/swup/swup-gia-demo) with async working just fine if you add it (with [this](https://webpack.js.org/guides/public-path/#use-cases) for the file to load from the correct URL of course). No babel is needed for Gia to work. For `default`, read [this page](https://webpack.js.org/guides/code-splitting/#dynamic-imports).

Don't tag people if they didn't reply to you first. People will reply when they have time to reply.
